# Numpy: 處理數學計算的好工具

## 參考資訊:
- https://numpy.org/
- 可以參考[手冊](https://numpy.org/doc/stable/)。
- 不錯的[切入點](https://numpy.org/doc/stable/user/absolute_beginners.html)。

## 我們假設你是使用 Anaconda，所以已經內建numpy
- 如果沒有的話，可以使用指令安裝 `pip install numpy`
----

## 為何需要numpy
- 很多科學運算都需要向量運算，但是原生的Python對這樣的操作並不方便
- 以C為基礎來開發的模組，速度快很多

### 起手式

In [1]:
import numpy as np

In [2]:
# 以 A+B來說

va = [1, 2, 3]
vb = [4, 5, 6]

va+vb

[1, 2, 3, 4, 5, 6]

In [3]:
# 我們要這樣寫
va = [1, 2, 3]
vb = [4, 5, 6]

vc = list()
for i in range(len(va)):
    vc.append(va[i]+vb[i])
print(vc)

[5, 7, 9]


In [4]:
# 以numpy來處理
va1 = np.array(va)
vb1 = np.array(vb)
va1+vb1

array([5, 7, 9])

### 乘法

In [5]:
va1*vb1

array([ 4, 10, 18])

### 建立二維的

In [6]:
a = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
    ])

In [8]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a[1]

array([5, 6, 7, 8])

### 談談: 1D array, 2D array, ndarray, vector, matrix
- ndarray 可呈現 1D, 2D, ... nD
- vector: 一維
- matrix: 二維
- tensor: 三維、或是更高維度的array


### 建立ndarray的方法
- 使用array()

In [9]:
X = [1, 2, 3]
Y = np.array(X)
Y

array([1, 2, 3])

In [10]:
X

[1, 2, 3]

In [11]:
A = np.array([4, 5, 6])
A

array([4, 5, 6])

- ndarray 的屬性

In [12]:
A.shape

(3,)

In [15]:
A.dtype

dtype('int32')

### 建立ndarray的方法
- np.array()
- np.zeros()
- np.ones()
- np.empty()
- np.arange()
- np.linspace()

In [13]:
import numpy as np
a = np.array([1, 2, 3])

In [14]:
a

array([1, 2, 3])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros(3).dtype

dtype('float64')

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.empty(2) #The function empty creates an array whose initial content is random and depends on the state of the memory

array([1.93719321e-147, 2.02909009e+158])

In [21]:
np.arange(4) # 可以想像成是range(4)的numpy版

array([0, 1, 2, 3])

In [23]:
np.arange(2, 9, 2) # 也可以像 range那樣給(start, end, step)

array([2, 4, 6, 8])

In [22]:
np.linspace(0, 10, num=5) #to create an array with values that are spaced linearly in a specified interval

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(0, 10, num=20) #to create an array with values that are spaced linearly in a specified interval

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
x = np.ones(2, dtype=np.int64) #可以指定dtype的型態

In [25]:
x

array([1, 1], dtype=int64)

In [27]:
np.ones(2) #the default data type is floating point (np.float64)

array([1., 1.])

### sort操作

In [28]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [29]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### array 

In [31]:
va = [1, 2, 3, 4]
vb = [5, 6, 7, 8]
va+vb

[1, 2, 3, 4, 5, 6, 7, 8]

In [30]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
a+b

array([ 6,  8, 10, 12])

In [33]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
list_a = [[1, 2, 3], ['a', 'b'], [1], [5, 6, 7, 8, 9, 10]]

In [38]:
list_a

[[1, 2, 3], ['a', 'b'], [1], [5, 6, 7, 8, 9, 10]]

In [36]:
np.concatenate((x, y), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### ndim, size, shape

In [39]:
array_example = np.array([
                            [[0, 1, 2, 3],
                             [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [40]:
array_example.ndim

3

In [41]:
array_example.size

24

In [42]:
array_example.shape

(3, 2, 4)

### reshape

In [43]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [44]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

### index, slice

In [45]:
data = np.array([1, 2, 3, 4, 5])

In [46]:
data[1]

2

In [49]:
data[0:4]

array([1, 2, 3, 4])

In [50]:
data[3:]

array([4, 5])

In [51]:
data[-4:4]

array([2, 3, 4])

- Broadcasting

In [69]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [52]:
v1 = np.array([1.0, 2.0])
v2 = np.array([1.6, 1.6])
v1*v2

array([1.6, 3.2])

### More useful array operations

In [72]:
data = np.array([4, 5, 6, 7, 8, 9, 10])

In [73]:
data.max()

10

In [74]:
data.min()

4

In [75]:
data.sum()

49

In [76]:
data.mean()

7.0

In [77]:
data.prod()

604800

- 對上matrix的操作

In [78]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [79]:
a.sum()

4.8595784

In [80]:
a.mean()

0.4049648666666667

In [81]:
a.min()

0.05093587

- 這邊很像excel中 column方向，或是row方向的操作

In [82]:
a.sum(axis=0)

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])

In [83]:
a.sum(axis=1)

array([1.51832856, 1.55434556, 1.78690428])

In [84]:
a.mean(axis=0)

array([0.37459419, 0.34958502, 0.33678154, 0.55889871])

In [84]:
a.mean(axis=1)

array([0.37958214, 0.38858639, 0.44672607])

In [85]:
# TODO: 練習以這一個matrix進行sum, mean, min, max的操作
# 假設以下是一個班級學生的考試成績
#                國文, 數學
data = np.array([[80, 60], # A君
                 [85, 66], # B君
                 [90, 90], # C君
                 [70, 92], # D君
                 [82, 80]  # E君
                ])


In [86]:
# 全班國文的平均
data.mean(axis=0)

array([81.4, 77.6])

In [90]:
data.sum(axis=1)

array([140, 151, 180, 162, 162])

In [89]:
# 全班每一位同學的總分
data.sum(axis=1).max()

180

### 進一步做比較

In [91]:
a = np.array([[1 , 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

In [92]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [93]:
print(a[a < 5])

[1 2 3 4]


In [96]:
print(a[a > 5])

[ 6  7  8  9 10 11 12]


In [97]:
m1 = [[1 , 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]]
for i in range(3):
    for j in range(4):
        if m1[i][j]<5:
            print(m1[i][j])

1
2
3
4


In [100]:
divisible_by_2 = a[a%7==0]
divisible_by_2

array([7])

In [101]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


- where

In [102]:
np.where(a>5, a, 0)

array([[ 0,  0,  0,  0],
       [ 0,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
b = np.array([[1 , 1, 1, 1], 
              [1, 1, 1, 1], 
              [1, 1, 1, 1]])
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [104]:
np.where(a>5, a, b)

array([[ 1,  1,  1,  1],
       [ 1,  6,  7,  8],
       [ 9, 10, 11, 12]])